/*
 * Copyright 2014-2015 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define BUILD_VERSION                  "0.7.1-SNAPSHOT"
# define BUILD_COMMIT_HASH              ""

# define APPLICATION_TOKEN              "61567828259699923455"

# define CONFIG_SCHEMA_VERSION          1
# define PROFILE_SCHEMA_VERSION         1
# define SYSTEM_NF_SCHEMA_VERSION       1
# define USER_NF_SCHEMA_VERSION         1
# define LOG_SCHEMA_VERSION             1


# define KAA_SYNC_TIMEOUT               60000L



typedef struct {
    const char *    name;
    uint16_t         version;
} kaa_events_schema_version_t;

# define KAA_EVENT_SCHEMA_VERSIONS_SIZE    1

static const kaa_events_schema_version_t KAA_EVENT_SCHEMA_VERSIONS[KAA_EVENT_SCHEMA_VERSIONS_SIZE] = {
    {
          /* .name = */   "movement"
        , /* .version = */2
    }};



/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x95f7e40f,
            338,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -119 , 87 , -104 , -97 , -9 , -37 , -56 , 114 , 41 , -5 , -65 , 45 , 37 , 50 , 23 , -89 , 47 , 90 , -99 , -39 , 33 , 71 , -46 , -29 , -83 , -22 , 121 , -43 , 39 , -115 , -54 , 123 , -70 , -90 , 56 , -114 , -19 , 122 , 110 , 125 , 60 , 97 , 44 , 39 , 90 , 119 , 55 , 8 , 109 , -120 , -70 , -91 , -95 , 7 , 17 , -70 , -112 , -4 , 9 , -112 , -117 , 102 , 53 , -103 , -103 , -92 , 119 , 15 , 46 , -18 , -32 , -52 , -113 , 50 , -10 , -27 , 5 , -71 , -104 , -98 , -1 , 103 , -53 , 96 , 108 , 48 , -113 , 3 , 77 , -49 , -71 , -5 , -24 , -89 , 6 , -113 , -40 , 116 , -37 , -81 , -68 , 29 , 15 , 13 , -38 , -50 , 44 , 22 , -50 , 37 , -51 , 47 , -21 , -34 , 110 , 19 , -8 , 14 , -19 , 95 , -1 , 104 , 69 , -34 , -23 , -48 , -115 , -17 , 6 , 54 , -107 , 51 , -35 , 20 , -77 , 107 , -69 , -105 , 36 , -1 , 35 , -16 , 9 , -59 , -76 , -25 , 84 , -57 , -121 , -82 , -31 , -22 , 51 , 35 , -121 , 31 , 54 , -102 , 101 , -3 , 85 , 66 , 50 , 4 , 24 , 65 , -92 , -1 , 106 , -47 , 51 , -38 , -5 , -80 , 111 , -48 , -76 , 67 , 68 , 50 , 95 , -65 , 97 , -39 , 86 , 116 , -120 , -69 , 118 , -111 , 100 , 75 , 66 , -21 , -58 , 33 , 115 , -75 , 6 , 43 , 37 , 82 , -97 , -24 , 2 , -81 , -21 , 18 , 124 , 21 , -8 , -18 , -102 , -126 , -29 , -68 , 114 , 70 , -60 , 21 , -85 , 67 , 36 , 103 , -46 , -63 , -21 , -55 , 25 , -110 , 101 , -78 , 68 , -84 , 57 , -47 , -27 , 46 , -77 , 25 , 44 , -7 , 48 , -127 , 23 , -47 , -61 , 103 , -55 , -87 , 2 , 49 , 104 , 21 , 92 , -41 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 32 , 107 , 97 , 97 , 45 , 100 , 101 , 109 , 111 , 45 , 111 , 110 , 101 , 46 , 99 , 121 , 98 , 101 , 114 , 118 , 105 , 115 , 105 , 111 , 110 , 116 , 101 , 99 , 104 , 46 , 99 , 111 , 109 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x95f7e40f,
            338,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -119 , 87 , -104 , -97 , -9 , -37 , -56 , 114 , 41 , -5 , -65 , 45 , 37 , 50 , 23 , -89 , 47 , 90 , -99 , -39 , 33 , 71 , -46 , -29 , -83 , -22 , 121 , -43 , 39 , -115 , -54 , 123 , -70 , -90 , 56 , -114 , -19 , 122 , 110 , 125 , 60 , 97 , 44 , 39 , 90 , 119 , 55 , 8 , 109 , -120 , -70 , -91 , -95 , 7 , 17 , -70 , -112 , -4 , 9 , -112 , -117 , 102 , 53 , -103 , -103 , -92 , 119 , 15 , 46 , -18 , -32 , -52 , -113 , 50 , -10 , -27 , 5 , -71 , -104 , -98 , -1 , 103 , -53 , 96 , 108 , 48 , -113 , 3 , 77 , -49 , -71 , -5 , -24 , -89 , 6 , -113 , -40 , 116 , -37 , -81 , -68 , 29 , 15 , 13 , -38 , -50 , 44 , 22 , -50 , 37 , -51 , 47 , -21 , -34 , 110 , 19 , -8 , 14 , -19 , 95 , -1 , 104 , 69 , -34 , -23 , -48 , -115 , -17 , 6 , 54 , -107 , 51 , -35 , 20 , -77 , 107 , -69 , -105 , 36 , -1 , 35 , -16 , 9 , -59 , -76 , -25 , 84 , -57 , -121 , -82 , -31 , -22 , 51 , 35 , -121 , 31 , 54 , -102 , 101 , -3 , 85 , 66 , 50 , 4 , 24 , 65 , -92 , -1 , 106 , -47 , 51 , -38 , -5 , -80 , 111 , -48 , -76 , 67 , 68 , 50 , 95 , -65 , 97 , -39 , 86 , 116 , -120 , -69 , 118 , -111 , 100 , 75 , 66 , -21 , -58 , 33 , 115 , -75 , 6 , 43 , 37 , 82 , -97 , -24 , 2 , -81 , -21 , 18 , 124 , 21 , -8 , -18 , -102 , -126 , -29 , -68 , 114 , 70 , -60 , 21 , -85 , 67 , 36 , 103 , -46 , -63 , -21 , -55 , 25 , -110 , 101 , -78 , 68 , -84 , 57 , -47 , -27 , 46 , -77 , 25 , 44 , -7 , 48 , -127 , 23 , -47 , -61 , 103 , -55 , -87 , 2 , 49 , 104 , 21 , 92 , -41 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 32 , 107 , 97 , 97 , 45 , 100 , 101 , 109 , 111 , 45 , 111 , 110 , 101 , 46 , 99 , 121 , 98 , 101 , 114 , 118 , 105 , 115 , 105 , 111 , 110 , 116 , 101 , 99 , 104 , 46 , 99 , 111 , 109 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    17

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
0 , -90 , -69 , 28 , -106 , 125 , 56 , 76 , 0 , -73 , 102 , -35 , -115 , 52 , 91 , 70 , -100 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

